export default Object.freeze({
  SHOW_ERROR: 'SHOW_ERROR',
  
  SORT_COIN_LIST: 'SORT_COIN_LIST',
  SORT_COIN_LIST_SUCCESS: 'SORT_COIN_LIST_SUCCESS',
  
  GET_COIN_LIST: 'GET_COIN_LIST',
  GET_COIN_LIST_SUCCESS: 'GET_COIN_LIST_SUCCESS',
  GET_LIST_FAILURE: 'GET_LIST_FAILURE'
});