export default Object.freeze({
  SHOW_ERROR: 'SHOW_ERROR',
  
  SORT_SYMBOL_LIST: 'SORT_SYMBOL_LIST',
  SORT_SYMBOL_LIST_SUCCESS: 'SORT_SYMBOL_LIST_SUCCESS',
  
  GET_MARKET_LIST: 'GET_MARKET_LIST',
  GET_MARKET_LIST_SUCCESS: 'GET_MARKET_LIST_SUCCESS',
  GET_LIST_FAILURE: 'GET_LIST_FAILURE'
});