export default Object.freeze({
  SHOW_ERROR: 'SHOW_ERROR',
  
  SORT_SYMBOL_LIST: 'SORT_SYMBOL_LIST',
  SORT_SYMBOL_LIST_SUCCESS: 'SORT_SYMBOL_LIST_SUCCESS',
  
  GET_MARKET_LIST: 'GET_MARKET_LIST',
  GET_MARKET_LIST_SUCCESS: 'GET_MARKET_LIST_SUCCESS',
  GET_LIST_FAILURE: 'GET_LIST_FAILURE',

  SEARCH_SYMBOL: 'SEARCH_SYMBOL',

  // SOCKET
  LISTEN_PUBLIC_SOCKET_EVENT: 'LISTEN_PUBLIC_SOCKET_EVENT',
  LISTEN_PRIVATE_SOCKET_EVENT: 'LISTEN_PRIVATE_SOCKET_EVENT',
  UPDATE_SOCKET_DATA_SUCCESS: 'UPDATE_SOCKET_DATA_SUCCESS',
  UPDATE_MARKET_LIST_SUCCESS: 'UPDATE_MARKET_LIST_SUCCESS',
  UPDATE_BALANCE_SUCCESS: 'UPDATE_BALANCE_SUCCESS',
  UPDATE_ORDER_BOOK_SUCCESS: 'UPDATE_ORDER_BOOK_SUCCESS',
  TRANSACTION_CREATED_SUCCESS: 'TRANSACTION_CREATED_SUCCESS',
  ORDER_TRANSACTION_CREATED_SUCCESS: 'ORDER_TRANSACTION_CREATED_SUCCESS',
  UPDATE_ORDER_BOOK_SUCCESS: 'UPDATE_ORDER_BOOK_SUCCESS',
  UPDATE_ORDER_LIST_SUCCESS: 'UPDATE_ORDER_LIST_SUCCESS',
  ORDER_CHANGED_SUCCESS: 'ORDER_CHANGED_SUCCESS',
  USER_SESSION_REGISTERED_SUCCESS: 'USER_SESSION_REGISTERED_SUCCESS'

});